Add FreeBSD 11 csh compatibility

diff --git a/tcpping b/tcpping
--- a/tcpping
+++ b/tcpping
@@ -39,8 +39,8 @@
 # 2019/09/25 v2.3 allow -w parameter to take floats
 #                 added -o parameter, which outputs statistics similar to ping
 #                 Simpify main loop
+#                 fix ambiguous output redirect in csh for preflight check
 
-# TODO            Simplify code, improve variable names, uniform `expr ` and $(( )) statements
 
 ver="v2.3"
 format="%Y%m%d%H%M%S"
@@ -62,6 +62,7 @@ METHOD=tcp
 protoOptions="-T"
 proto=tcp
 summary="no"
+x=0
 
 # Make sure traceroute output is language agnostic
 export LANG=C
@@ -105,11 +106,11 @@ getLocalOS() {
 		if grep -i Microsoft /proc/sys/kernel/osrelease > /dev/null 2>&1; then
 			localOsVar="Microsoft"
 		else
-			localOsVar="$(uname -spior 2>&1)"
+			localOsVar="`uname -spior 2>&1`"
 			if [ $? != 0 ]; then
-				localOsVar="$(uname -v 2>&1)"
+				localOsVar="`uname -v 2>&1`"
 				if [ $? != 0 ]; then
-					localOsVar="$(uname)"
+					localOsVar="`uname`"
 				fi
 			fi
 		fi
@@ -148,9 +149,14 @@ getLocalOS() {
 }
 
 checkEnvironment() {
-	if ! type traceroute > /dev/null 2>&1 ; then
+	if ! type traceroute > /dev/null; then
 		echo >&2 "traceroute binary not found. Please install it first"
 		exit 1
+	fi
+	
+	if ! type awk > /dev/null; then
+		echo >&2 "awk binary not found. Please install it first"
+		exit 2
 	fi
 }
 
@@ -178,7 +184,7 @@ _checkSite() {
 
 	traceRoute=`$traceRouteCommand 2>&1`
 	if [ $? -ne 0 ]; then
-		if [ "$(id -u)" -ne 0 ]; then
+		if [ "`id -u`" -ne 0 ]; then
 			echo >&2 "Unable to run '$traceRouteCommand' command. Please try run $0 with -Z parameter or 'sudo $0'"
 			return 20
 		else
@@ -320,12 +326,8 @@ if [ "${summary}" == "yes" ]; then
 	trap _quit SIGQUIT EXIT
 fi
 
-# Check if timeToWait is float, if yes, use maybe less portable awk version
-if [ "${timeToWait}" != "${timeToWait/./}" ]; then
-        max=$(awk 'BEGIN{printf "%.2f\n", ('${timeToWait}'*1000)}')
-else
-        max=$((${timeToWait} * 1000))
-fi
+# Use awk to multiply possible float in timeToWait
+max=`awk 'BEGIN{printf "%.2f\n", ('${timeToWait}'*1000)}'`
 
 if [ `date +%s` != "%s" ]; then
 	format="%s"
@@ -333,7 +335,6 @@ fi
 
 getLocalOS
 
-#WIP check here
 if [ "$LOCAL_OS" = "BSD" ] || [ "$LOCAL_OS" = "MacOSX" ]; then
 	METHOD_PARAMETER="-P"
 else
@@ -369,11 +370,8 @@ err=$?
 
 pingCount=0
 pingFailCount=0
-if [ "$x" = "" ]; then
-        x=-1
-fi
 
-while [ "$x" -gt 0 ] || [ "$x" -le -1 ]; do
+while [ $pingCount -lt $x ] || [ $x -eq 0 ]; do
 	result=""
 	_testSite "${host}" "${port}" ${seq} ${topt} &
 	pid=$!
@@ -386,8 +384,7 @@ while [ "$x" -gt 0 ] || [ "$x" -le -1 ]; do
 	if [ $seq -gt 0 ]; then
 		_DEBUG=false
 	fi
-	x=`expr $x - 1`
-	if [ "$x" -gt 0 ] || [ "$x" -le -1 ]; then
+	if [ $pingCount -lt $x ] || [ $x -eq 0 ]; then
 		sleep ${repeatWaitTime}
 	fi
 	if [ "$result" == "" ]; then
@@ -395,9 +392,9 @@ while [ "$x" -gt 0 ] || [ "$x" -le -1 ]; do
 		result=$?
 	fi
 
-	pingCount=$((pingCount+1))
+	pingCount=`expr $pingCount + 1`
 	if [ $result -ne 0 ]; then
-		pingFailCount=$((pingFailCount+1))
+		pingFailCount=`expr $pingFailCount + 1`
 	fi
 done
 
