Fixed wrong sudo option in output

diff --git a/tcpping b/tcpping
--- a/tcpping
+++ b/tcpping
@@ -177,7 +177,7 @@ _checkSite() {
 	traceRoute=`$traceRouteCommand 2>&1`
 	if [ $? -ne 0 ]; then
 		if [ "$(id -u)" -ne 0 ]; then
-			echo >&2 "Unable to run '$traceRouteCommand' command. Please try run $0 with -s parameter or 'sudo $0'"
+			echo >&2 "Unable to run '$traceRouteCommand' command. Please try run $0 with -Z parameter or 'sudo $0'"
 			return 20
 		else
 			echo >&2 "Unable to run '$traceRouteCommand' command. Please submit an issue in 'https://github.com/deajan/tcpping/issues'"
