Don't allow udp/icmp for tcptraceroute on other than BSD/MacOS

diff --git a/tcpping b/tcpping
--- a/tcpping
+++ b/tcpping
@@ -198,7 +198,7 @@ checkEnvironment() {
 
 # Check if site can be reached via TCP SYN
 
-# Measure latency via TCP SYN
+# Measure latency via TCP SYN / UDP / ICMP
 _testSite() {
 	local host="${1}"
 	local port="${2:-80}"
@@ -227,6 +227,10 @@ _testSite() {
 	[ "${d}" = "yes" ] && nowd=`date`
 
 	if [ "$traceRouteImplementation" = "tcptraceroute" ]; then
+		if [ "${METHOD}" != "tcp" ] && [ "$LOCAL_OS" != "BSD" ] && [ "$LOCAL_OS" != "MacOSX" ]; then
+			echo echo >&2 "Cannot use ${traceRouteBinary} with method ${method}. Please use traceroute"
+			exit 23
+		fi
 		traceRouteCommand="$SUDO_COMMAND${traceRouteBinary} -f ${f_ttl} -m ${m_ttl} -q ${numberOfQueries} -w ${timeToWait} ${args} ${host} ${port}"
 	else
 		traceRouteCommand="$SUDO_COMMAND${traceRouteBinary} ${METHOD_PARAMETER} ${METHOD} -f ${f_ttl} -m ${m_ttl} -q ${numberOfQueries} -w ${timeToWait} ${args} -p ${port} ${host}"
